# Generated by Django 2.1.15 on 2020-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200417_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
