# Generated by Django 2.1.15 on 2020-04-21 08:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(upload_to=blog.models.Contact.renommage, verbose_name='photo'),
        ),
    ]
